/* This file is auto-generated by (yogi loader --yes --start /home/graham/source/books/webapp/src/main/scripts --json /home/graham/source/books/webapp/target/webapp/scripts/loader.json --js /home/graham/source/books/webapp/target/webapp/scripts/loader.js) */
/*jshint maxlen:900, eqeqeq: false */
var add = Y.Features.add;
